### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by zeyutang** [mikeckennedy/python-switch#7]
Hi, I encountered the problem when I try to `from switchlang import switch`:
```
>>> from switchlang import switch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "switchlang.py", line 22
    def default(self, func: Callable[[], Any]):
                          ^
SyntaxError: invalid syntax
```
I am using python2.7.13.

Any ideas? Thx~

**Comment by mikeckennedy** [comment]
Hi, yes the problem is you're using Python 2. This only supports Python 3. Sorry.
